name = "Palm Kanban Board"
skipFolders = [ "node_modules", ".vscode", "out", "dist", ".vscode-test" ]
skipFiles = [ ".gitignore", "package.json" ]

[[processes]]
id = "process1"
name = "To Do"

  [[processes.tasks]]
  id = "abs7kz9kitlt9f4fdd9t16g4"
  title = "Add better logging"
  description = ""
  tag = "backlog"
  linkFiles = [ ]
  dueDate = ""
  checkList = [ ]
  priority = ""
  linkCommits = [ ]

  [[processes.tasks]]
  id = "u0rs6ogpym30zr94zcewbju0"
  title = "Skia init: Stencil size & num of samples utility functions"
  description = ""
  tag = "backlog"
  linkFiles = [ ]
  dueDate = ""
  checkList = [ ]
  priority = ""
  linkCommits = [ ]

  [[processes.tasks]]
  id = "vhh5vex2eg2p50agb9peh4vz"
  title = "Windows specific error types & handling"
  description = ""
  tag = "backlog"
  linkFiles = [ ]
  dueDate = ""
  checkList = [ ]
  priority = ""
  linkCommits = [ ]

[[processes]]
id = "process2"
name = "In Progress"
tasks = [ ]

[[processes]]
id = "process3"
name = "Done"

  [[processes.tasks]]
  id = "gz7oj0bqeuipy5juvfp5nguj"
  title = "Connect skia with win api window"
  description = "<p></p>"
  tag = "backlog"
  linkFiles = [ ]
  dueDate = ""
  checkList = [ ]
  priority = ""
  linkCommits = [ ]

  [[processes.tasks]]
  id = "ya0ph01es2wxj82r1ps35fan"
  title = "Resize is not handled properly"
  description = ""
  tag = "bug"
  linkFiles = [ ]
  dueDate = ""
  checkList = [ ]
  priority = ""
  linkCommits = [ ]

  [[processes.tasks]]
  id = "veux8eigi922dux6i0k0v23q"
  title = "Add a struct to pass into wndproc from run_window_loop"
  description = "<p></p>"
  tag = "backlog"
  linkFiles = [ ]
  dueDate = ""
  checkList = [ ]
  priority = ""
  linkCommits = [ ]

  [[processes.tasks]]
  id = "egbk8rgndguvc76wepsnihpe"
  title = "Add better docs"
  description = ""
  tag = "backlog"
  linkFiles = [ ]
  dueDate = ""
  checkList = [ ]
  priority = ""
  linkCommits = [ ]

  [[processes.tasks]]
  id = "ujez3x2od1dhumvbdcg4ruw0"
  title = "Create a less platform specific architecture"
  description = ""
  tag = "backlog"
  linkFiles = [ ]
  dueDate = ""
  checkList = [ ]
  priority = ""
  linkCommits = [ ]

  [[processes.tasks]]
  id = "dbyatfwt99cfb5aqclvxojbl"
  title = "Initialise GL context in window"
  description = ""
  tag = "backlog"
  linkFiles = [ ]
  dueDate = ""
  checkList = [ ]
  priority = ""
  linkCommits = [ ]

  [[processes.tasks]]
  id = "olglev4p7djju0lzj08g00wa"
  title = "Create a window using the win api"
  description = "<p></p>"
  tag = "backlog"
  linkFiles = [ ]
  dueDate = ""
  checkList = [ ]
  priority = ""
  linkCommits = [ ]

  [[processes.tasks]]
  id = "y8awubprcxdvm63okvxssz6l"
  title = "Panic on window close"
  description = ""
  tag = "bug"
  linkFiles = [ ]
  dueDate = ""
  checkList = [ ]
  priority = ""
  linkCommits = [ ]

  [[processes.tasks]]
  id = "t8kc03dmyhjczgni7dcq4j7c"
  title = "Add basic absolute position widgets"
  description = ""
  tag = "backlog"
  linkFiles = [ ]
  dueDate = ""
  checkList = [ ]
  priority = ""
  linkCommits = [ ]

  [[processes.tasks]]
  id = "ewvywzutfw8idwjlczx8f45u"
  title = "Platform agnostic skia impl"
  description = ""
  tag = "backlog"
  linkFiles = [ ]
  dueDate = ""
  checkList = [ ]
  priority = ""
  linkCommits = [ ]

[[processes]]
id = "dx64kht496va25bpkxl7xx6w"
name = "Not Sure"

  [[processes.tasks]]
  id = "dayggersw784twz3kvswvkso"
  title = "Investigate selective redraw"
  description = ""
  tag = "backlog"
  linkFiles = [ ]
  dueDate = ""
  checkList = [ ]
  priority = ""
  linkCommits = [ ]

  [[processes.tasks]]
  id = "rlneg193x8j5ecbfshp1akzp"
  title = "Investigate skia-safe >0.75 issues"
  description = ""
  tag = "bug"
  linkFiles = [ ]
  dueDate = ""
  checkList = [ ]
  priority = ""
  linkCommits = [ ]

  [[processes.tasks]]
  id = "a1p8lud0qq2d0lct2pgk8c21"
  title = "Window initially displays blank frame before renderer is invoked"
  description = ""
  tag = "bug"
  linkFiles = [ ]
  dueDate = ""
  checkList = [ ]
  priority = ""
  linkCommits = [ ]

[[processes]]
id = "e0wdhdale0t29zlrkjhohoui"
name = "Nice To Have"

  [[processes.tasks]]
  id = "pfjxkv66l54r0vbzuch7v0ex"
  title = "Skia anti-aliasing?"
  description = ""
  tag = "backlog"
  linkFiles = [ ]
  dueDate = ""
  checkList = [ ]
  priority = ""
  linkCommits = [ ]
