name = "project"
skipFolders = [ "node_modules", ".vscode", "out", "dist", ".vscode-test" ]
skipFiles = [ ".gitignore", "package.json" ]

[[processes]]
id = "process1"
name = "To Do"

  [[processes.tasks]]
  id = "abs7kz9kitlt9f4fdd9t16g4"
  title = "Add better logging"
  description = ""
  tag = "backlog"
  linkFiles = [ ]
  dueDate = ""
  checkList = [ ]
  priority = ""
  linkCommits = [ ]

  [[processes.tasks]]
  id = "t8kc03dmyhjczgni7dcq4j7c"
  title = "Add basic absolute position widgets"
  description = ""
  tag = "backlog"
  linkFiles = [ ]
  dueDate = ""
  checkList = [ ]
  priority = ""
  linkCommits = [ ]

[[processes]]
id = "process2"
name = "In Progress"

  [[processes.tasks]]
  id = "gz7oj0bqeuipy5juvfp5nguj"
  title = "Connect skia with win api window"
  description = "<p></p>"
  tag = "backlog"
  linkFiles = [ ]
  dueDate = ""
  priority = ""
  linkCommits = [ ]

    [[processes.tasks.checkList]]
    id = "qpvr39d5eki9o70aznvv2xoc"
    title = ""
    completed = false

[[processes]]
id = "process3"
name = "Done"

  [[processes.tasks]]
  id = "egbk8rgndguvc76wepsnihpe"
  title = "Add better docs"
  description = ""
  tag = "backlog"
  linkFiles = [ ]
  dueDate = ""
  checkList = [ ]
  priority = ""
  linkCommits = [ ]

  [[processes.tasks]]
  id = "ujez3x2od1dhumvbdcg4ruw0"
  title = "Create a less platform specific architecture"
  description = ""
  tag = "backlog"
  linkFiles = [ ]
  dueDate = ""
  checkList = [ ]
  priority = ""
  linkCommits = [ ]

  [[processes.tasks]]
  id = "dbyatfwt99cfb5aqclvxojbl"
  title = "Initialise GL context in window"
  description = ""
  tag = "backlog"
  linkFiles = [ ]
  dueDate = ""
  checkList = [ ]
  priority = ""
  linkCommits = [ ]

  [[processes.tasks]]
  id = "olglev4p7djju0lzj08g00wa"
  title = "Create a window using the win api"
  description = "<p></p>"
  tag = "backlog"
  linkFiles = [ ]
  dueDate = ""
  checkList = [ ]
  priority = ""
  linkCommits = [ ]

  [[processes.tasks]]
  id = "y8awubprcxdvm63okvxssz6l"
  title = "Panic on window close"
  description = ""
  tag = "bug"
  linkFiles = [ ]
  dueDate = ""
  checkList = [ ]
  priority = ""
  linkCommits = [ ]

[[processes]]
id = "dx64kht496va25bpkxl7xx6w"
name = "Not sure"

  [[processes.tasks]]
  id = "ewvywzutfw8idwjlczx8f45u"
  title = "Platform agnostic skia impl"
  description = ""
  tag = "backlog"
  linkFiles = [ ]
  dueDate = ""
  checkList = [ ]
  priority = ""
  linkCommits = [ ]

  [[processes.tasks]]
  id = "dayggersw784twz3kvswvkso"
  title = "Investigate selective redraw"
  description = ""
  tag = "backlog"
  linkFiles = [ ]
  dueDate = ""
  checkList = [ ]
  priority = ""
  linkCommits = [ ]
